version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
      args:
        PYTHON_VARIANT: 3.8-bookworm
    ports:
      - '4040:4040'
    volumes:
      - ..:/workspace
      - ..:/opt/spark/work-dir
    command: sleep infinity
  
  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-07T00-43-48Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  minio_data: {}